version: '3.8'
services:
  backend:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      MONGO_URI: "${MONGO_URI_DOCKER}"
      PORT: "${PORT}"
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - restapi:/data/db

volumes: 
  restapi:
